name: dotlvn-woometrics

networks:
  dotlvn-network:
    external: true

services:
  # WooCommerce Prometheus Exporter
  woometrics:
    build: .
    container_name: woometrics
    restart: unless-stopped
    networks:
      - dotlvn-network
    ports:
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./src/config:/app/src/config:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s