name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
  
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.0 (Default)
        - 0.1.0
        - development/main branch
    validations:
      required: true
  
  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running the application?
      options:
        - Docker (Recommended)
        - Docker Compose
        - Node.js directly
        - Kubernetes
        - Other
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide details about your environment
      placeholder: |
        - OS: (e.g., Ubuntu 20.04, Windows 10, macOS 12.0)
        - Node.js version: (e.g., 18.17.0)
        - Docker version: (if applicable)
        - WooCommerce version: (e.g., 8.2.0)
        - Number of stores configured: (e.g., 3)
      value: |
        - OS: 
        - Node.js version: 
        - Docker version: 
        - WooCommerce version: 
        - Number of stores: 
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Start the application with '...'
        2. Navigate to '...'
        3. Click on '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true
  
  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please share your configuration (remove sensitive data like API keys)
      placeholder: |
        Environment variables:
        - PORT=9090
        - LOG_LEVEL=info
        - SCRAPE_INTERVAL=*/5 * * * *
        - STORE1_URL=https://example.com
        
        Docker command or docker-compose.yml snippet (if applicable)
      render: yaml
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/your-org/woometrics/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true