blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/your-org/woometrics/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/your-org/woometrics/tree/main/docs
    about: Check our comprehensive documentation
  - name: 🔒 Security Issues
    url: https://github.com/your-org/woometrics/blob/main/SECURITY.md
    about: Report security vulnerabilities privately